# ----
# Site

title: Archeotech Joinville
url: https://www.archeotech.com.br
baseurl:
google_analytics_key:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Projeto Arqueotech de Joinville, Santa Catarina
author:
  name:
  email:
  twitter: # twitter username without the @ symbol
social:
  name: Archeotech Joinville
  links:
    - https://github.com/archeotech-joinville

# -----
# Build

timezone: Etc/UTC

collections:
  staff_members:
    _hide_content: true
    _options:
      image:
        width: 250
        height: 250

permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      _options:
        content:
          width: 1880
          height: 1880
  -
    scope:
      path: ""
    values:
      layout: "default"

donation_embed:
newsletter_action: "//your-mailchimp-action-url.com"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# -----------
# CloudCannon

_options:
  header_background_image:
    width: 1880
    height: 1880
  newsletter_background_image:
    width: 1880
    height: 1880
